### ISSUE TITLE
Epic: test coverage for content pages

### ISSUE THREAD

**Issue by ryanj** [openshift-evangelists/kbe#52]
TODO:

v1: local content validation (BYO cluster credentials)
- [x] find markdown files, foreach file{
- [ ] parse and extract example commands
- [ ] parse example responses
- [ ] establish test cases to ensure commands do not fail or return an error when executed in order
- [ ] add test cases to compare example response output with actual response output, report any diffs
- [ ] provide the date, time, and k8s API version that was most recently used to validate the content #26, #63

v2: test automation
- [ ] automated updates of example responses
- [ ] automated test coverage (nightly)
- [ ] report results of test runs
  - [ ] via GitHub repo
  - [ ] new /status page? 

v3:
- [ ] include separate reports per k8s release (cover last three releases of K8s)?
- [ ] include separate reports for the two most recent releases of OpenShift?
- [ ] investigate opportunities to contribute to, or borrow examples from upstream k8s test coverage examples
