### ISSUE TITLE
The Basics: how to get kubectl, kubeconfigs, export env vars

### ISSUE THREAD

**Issue by ryanj** [openshift-evangelists/kbe#64]
Add a general `getting started` section to help guide users from `diy` to `pods`.

This page should:

- [ ] provide clear information on how to connect to the cluster (`kubeconfig`) #41, #60 
- [ ] provide clear information on how to download `kubectl` and how to add it to your `$PATH`
- [ ] establish a consistent namespace for running experiments #21
- [ ] work in coordination with #63 to help resolve: [#41, #21, #60, #26]

Also:
- [ ] Should provide information regarding the date, time, and k8s API version that was used to validate the content #26
